import type { Metadata } from "next";
import { DM_Sans, Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const dm_sans = DM_Sans({
  variable: "--font-dm_sans",
  subsets: ["latin"],
});

const bricolage_grotesque = Bricolage_Grotesque({
  variable: "--font-bricolage_grotesque",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Nadice oil & Gas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${dm_sans.variable} ${bricolage_grotesque.variable} h-full`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <section className="pt-24">
          {children}
        </section>
        <Footer />
      </body>
    </html>
  );
}
